### ISSUE TITLE
Very Slow Bee Movement

### ISSUE THREAD

**Issue by ghost** [noobanidus/carrier-bees#1]
Forge 31.1.47
CarrierBees 1.15.2-0.0.0.5

When summoned the Bees move really slowly. I assume they are supposed to have similar A.I to Vanilla Bees?

**Comment by noobanidus** [comment]
This is actually intentional. This mod is technically a commission for a stream author. I can perhaps make it so that their speed is configurable...

**Comment by ghost** [comment]
I can understand spawning a Bee holding a ChanceCube, but if its not going to move you may as well just spawn it with noAI, it doesnt make sense, theres no challenge if the bee is just going to sit there

In my opinion it what be more fun to have the bee move with 'bee-like' mechanics at least around the player, like a fox with a chancecube, at least you have to chase it

still its a nice idea of a mod

**Comment by noobanidus** [comment]
Like I said, the current implementation is based off feedback from the person who asked for the mod. Their priority is more the damage, effects, projectile, etc.
