### ISSUE TITLE
Startup crash with newest version (1.16.5)

### ISSUE THREAD

**Issue by Neko2n** [noobanidus/carrier-bees#5]
Starting up my game either results in a permanent freeze or, in lucky cases, an actual crash.

Here's the crash log text file. I have quite a few other mods installed that may be responsible for an incompatibility, so if it is an incompatibility please let me know.

https://pastebin.com/QjfXhrZV

**Comment by noobanidus** [comment]
Can you post the full log file?

**Comment by Neko2n** [comment]
Gotcha, here's the latest.log
https://pastebin.com/qYQRF2KN 
Also this
![image](https://user-images.githubusercontent.com/43053729/135945498-06008265-0743-4d7a-9784-b8add1dd18a6.png)

**Comment by noobanidus** [comment]
Looks like this is indeed a versioning issue with Registrate and Carrier Bees, I'll have to re-compile a new version with an updated Registrate in it and release that. Thanks for the heads-up!

Just as a note, from the log file it appears as though a coremod (wings?) is failing to find the instruction it was looking to replace; it's possible Sodium or another mod has affected this. I know that the Sodium port isn't an "official" port and that it can potentially cause issues as, as far as I'm aware, it isn't optimized for forge.

**Comment by Neko2n** [comment]
> Just as a note, from the log file it appears as though a coremod (wings?) is failing to find the instruction it was looking to replace; it's possible Sodium or another mod has affected this. I know that the Sodium port isn't an "official" port and that it can potentially cause issues as, as far as I'm aware, it isn't optimized for forge.

Wings is a mod I compiled from another person's github for a friend. I'm using it for personal use and won't be including it in my pack unless it officially updates on curseforge. I even had to compile it from a pull request as the newest version wouldn't even compile, so I'd assume it's pretty buggy. Unless it crashes or lags I think it'll be fine to use in a private server with my friends.

As for Sodium reforged, it seems to have just fully released on curseforge yesterday(?), and it now doesn't crash in my modpack, so I'm hoping it can replace Optifine, and honestly if there's ANY way I can stop using Optifine I want to take the risk. Thanks for the heads up, though, I'll make sure to be careful.

**Comment by noobanidus** [comment]
Should be fixed in the latest release, 0.0.5.11! I've also tested it locally outside of dev and it *is* functional. Please let me know if there are issues.
